# name | cmake target | description
demo|hmi_nexus_demo|主 Demo 应用
http_example|hmi_nexus_http_example|HTTP/HTTPS 基本请求与下载例程
http_async_example|hmi_nexus_http_async_example|HTTP 异步请求与下载例程
logger_example|hmi_nexus_logger_example|Logger 组件使用例程
json_example|hmi_nexus_json_example|JSON C++ 封装使用例程
wifi_example|hmi_nexus_wifi_example|Wi-Fi 管理组件使用例程
